"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Book_1 = require("./Book");
var Library_1 = require("./Library");
var myLibrary = new Library_1.Library();
var book1 = new Book_1.Book('harry potter', 'J.K', '101');
var book2 = new Book_1.Book('Clean Code', 'Robert Martin', '102', false);
myLibrary.addBook(book1);
myLibrary.addBook(book2);
myLibrary.listBooks();
myLibrary.removeBook('102');
myLibrary.listBooks();
